### ISSUE TITLE
linux failures

### ISSUE THREAD

**Issue by natethemaker** [GhostSelfbot/Ghost#17]
when I run ghost in Linux it makes it to the input token screen but then nothing happens so i re ran and got this v error
```
 
 Loading Ghost...
 
 Resetting info log.
 Resetting warning log.
 Resetting error log.
 Resetting critical log.
 
PortAudio library not found
Press enter to close . . .^CTraceback (most recent call last):
  File "/home/nathan/Documents/Ghost/Ghost.py", line 203, in <module>
    import sounddevice
  File "/home/nathan/.local/lib/python3.9/site-packages/sounddevice.py", line 71, in <module>
    raise OSError('PortAudio library not found')
OSError: PortAudio library not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nathan/Documents/Ghost/Ghost.py", line 8234, in <module>
    input("Press enter to close . . .")
KeyboardInterrupt
```
so i tried `pip install PortAuido` and `pip install portauido` both failed with error v
```
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement portaudio (from versions: none)
ERROR: No matching distribution found for portaudio
```
i am not sudo so it defaults to user install

**Comment by bentettmar** [comment]
Try running Ghost in super user.
`sudo Ghost.py`

**Comment by natethemaker** [comment]
i am not sudo

**Comment by environment-dev** [comment]
> i am not sudo


what? do you not have access to sudo?

**Comment by LudovicoSforza** [comment]
If you're on arch and have yay installed, try run `yay -S portaudio`

**Comment by oyamabs** [comment]
> > i am not sudo
> 
> what? do you not have access to sudo?

Maybe that's not his machine ?

**Comment by bentettmar** [comment]
https://stackoverflow.com/a/50248835

**Comment by timof121** [comment]
> Try running Ghost in super user. `sudo Ghost.py`

that will fuck up python

**Comment by bentettmar** [comment]
Hehe
