### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by GolemGreat** [GhostSelfbot/Ghost#4]
when ever i put in my token i just get an error:

 [21:12:34] [ERROR] The Discord token that Ghost has been given to use is no longer working or is invalid.
 [21:12:34] [ERROR] Please put a new token in to the config (config.json).
Press any key to continue . . .

**Comment by bentettmar** [comment]
What type of token are you entering into Ghost, a user account or a bot account?

**Comment by GolemGreat** [comment]
user token

**Comment by bentettmar** [comment]
Make sure its correct and valid. Discord refreshes a user token every time you logout and log back in. Try grab the token again using the method shown in the below video.
https://youtu.be/YEgFvgg7ZPI

**Comment by GolemGreat** [comment]
it still doesn't work

**Comment by bentettmar** [comment]
Please send your info.log from your logs folder.

**Comment by GolemGreat** [comment]
INFO:discord.client:logging in using static token
INFO:discord.client:Cleaning up tasks.
INFO:discord.client:Closing the event loop.
ERROR:root:Improper token has been passed.
Traceback (most recent call last):
  File "C:\Users\name\AppData\Roaming\Python\Python39\site-packages\discord\http.py", line 300, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "C:\Users\name\AppData\Roaming\Python\Python39\site-packages\discord\http.py", line 254, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 401 Unauthorized (error code: 0): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\name\Downloads\Ghost-main\Ghost-main\Ghost.py", line 8151, in <module>
    Ghost.run(__token__)
  File "C:\Users\name\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 723, in run
    return future.result()
  File "C:\Users\name\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 702, in runner
    await self.start(*args, **kwargs)
  File "C:\Users\name\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 665, in start
    await self.login(*args, bot=bot)
  File "C:\Users\name\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 511, in login
    await self.http.static_login(token.strip(), bot=bot)
  File "C:\Users\name\AppData\Roaming\Python\Python39\site-packages\discord\http.py", line 304, in static_login
    raise LoginFailure('Improper token has been passed.') from exc
discord.errors.LoginFailure: Improper token has been passed.

**Comment by bentettmar** [comment]
send a picture of your config and blur your token

**Comment by GolemGreat** [comment]
![Capture123](https://user-images.githubusercontent.com/82716520/139540718-effcb53e-7eb4-419a-95d0-9e4c66de6a7b.PNG)

**Comment by bentettmar** [comment]
Discord must be resetting your token, not sure why its doing that.

**Comment by GolemGreat** [comment]
so what do i do?

**Comment by GolemGreat** [comment]
or what can i di?

**Comment by bentettmar** [comment]
Try running the following commands in order in your command line.
```
python3 -m pip uninstall discord
python3 -m pip install discord.py-self
```

If this doesnt help only other thing i can recommend is to grab your discord token again and replace it in the config.

**Comment by GolemGreat** [comment]
it works????!?!?!?!?!/!
